image: ansible-ci/ansible
services:
    - ansible-ci/ubuntu14
       
stages:
  - build
  
test-plan:
  stage: build
  script:
    - mkdir -p roles/apache
    - apt-get install rsync -y
    - apt-get install sshpass -y
    - apt-get install curl -y
    - ssh-keygen -t rsa -C "ansible@soprasteria.com" -N "" -f /root/.ssh/id_rsa
    - sshpass -p 'root' ssh-copy-id -o StrictHostKeyChecking=no root@ansible-ci__ubuntu14
    - echo '[webserver]' >> /etc/ansible/hosts
    - echo 'ansible-ci__ubuntu14' >> /etc/ansible/hosts
    - ansible all -m ping
    - ansible ansible-ci__ubuntu14 --sudo -m raw -a "yum install -y python2 python-simplejson" 
    - cat /etc/ansible/hosts
    - rsync -ar --exclude=.git --exclude=roles . roles/fancy-ansible-role
    - ansible-playbook --syntax-check playbook.yml
    - ansible webserver -m setup 
    - ansible-playbook playbook.yml --limit webserver
    - curl http://ansible-ci__ubuntu14
